/* SPDX-FileCopyrightText: 2026 Blender Authors
 *
 * SPDX-License-Identifier: GPL-2.0-or-later */

/** \file
 * \ingroup shdnodes
 */

#include "node_shader_util.hh"
#include "node_util.hh"

#include "UI_interface_layout.hh"
#include "UI_resources.hh"

namespace blender {

namespace nodes::node_shader_water_ripples_cc {

static void node_declare(NodeDeclarationBuilder &b)
{
  b.is_function_node();
  b.add_input<decl::Vector>("Vector"_ustr)
      .default_value(float3{0.0f, 0.0f, 0.0f})
      .hide_value()
      .default_input_type(NODE_DEFAULT_INPUT_POSITION_FIELD)
      .description("Coordinates used to generate the water ripple effect");
  b.add_input<decl::Float>("Time"_ustr)
      .default_value(0.0f)
      .description("Animation time input for the ripple simulation");
  b.add_input<decl::Float>("Mode"_ustr)
      .default_value(0.0f)
      .available(false)
      .description("Internal mode input used to keep the GPU material state in sync");
  b.add_input<decl::Float>("Scale"_ustr).default_value(1.0f).description("Overall scale of the effect");
  b.add_input<decl::Float>("Intensity"_ustr)
      .default_value(1.0f)
      .description("Strength of the ripple displacement");
  b.add_input<decl::Float>("Speed"_ustr)
      .default_value(1.0f)
      .description("Animation speed of the ripples");
  b.add_input<decl::Float>("Detail"_ustr)
      .default_value(0.5f)
      .description("Controls the complexity of the generated pattern");
  b.add_input<decl::Float>("Bias"_ustr)
      .default_value(0.6f)
      .description("Bias shaping used by the droplet profile");
  b.add_output<decl::Vector>("Distorted Vector"_ustr)
      .description("Distorted coordinates generated by the ripple simulation");
  b.add_output<decl::Float>("Mask"_ustr).description("Ripple mask or intensity output");
}

static void node_layout(ui::Layout &layout, bContext * /*C*/, PointerRNA *ptr)
{
  layout.prop(ptr, "mode", ui::ITEM_R_SPLIT_EMPTY_NAME, std::nullopt, ICON_NONE);
}

static void node_init(bNodeTree * /*ntree*/, bNode *node)
{
  node->custom1 = NODE_WATER_RIPPLES_DROPS;
}

static void node_update(bNodeTree * /*ntree*/, bNode *node)
{
  bNodeSocket *mode_socket = bke::node_find_socket(*node, SOCK_IN, "Mode"_ustr);
  if (mode_socket == nullptr || mode_socket->default_value == nullptr) {
    return;
  }

  mode_socket->default_value_typed<bNodeSocketValueFloat>()->value = float(node->custom1);
}

static int gpu_shader_water_ripples(GPUMaterial *mat,
                                    bNode *node,
                                    bNodeExecData * /*execdata*/,
                                    GPUNodeStack *in,
                                    GPUNodeStack *out)
{
  node_shader_gpu_default_tex_coord(mat, node, &in[0].link);
  return GPU_stack_link(mat, node, "node_water_ripples", in, out);
}

}  // namespace nodes::node_shader_water_ripples_cc

void register_node_type_sh_water_ripples()
{
  namespace file_ns = nodes::node_shader_water_ripples_cc;

  static bke::bNodeType ntype;

  common_node_type_base(&ntype, "ShaderNodeWaterRipples"_ustr, SH_NODE_WATER_RIPPLES);
  ntype.ui_name = "Water Ripples";
  ntype.ui_description = "Generate procedural water ripple distortion and masks";
  ntype.enum_name_legacy = "WATER_RIPPLES";
  ntype.nclass = NODE_CLASS_TEXTURE;
  ntype.declare = file_ns::node_declare;
  ntype.draw_buttons = file_ns::node_layout;
  ntype.initfunc = file_ns::node_init;
  ntype.updatefunc = file_ns::node_update;
  ntype.gpu_fn = file_ns::gpu_shader_water_ripples;

  bke::node_register_type(ntype);
}

}  // namespace blender
